### ISSUE TITLE
Curator is a runtime dependency

### ISSUE THREAD

**Issue by crispywalrus** [krasserm/akka-persistence-kafka#21]
Nothing huge here but curator is being delivered as a runtime dependency. I'll submit a pull request with curator and test server moved to test config

**Comment by krasserm** [comment]
Curator is used for running a [test server](https://github.com/krasserm/akka-persistence-kafka#test-server) i.e. the runtime dependency was intentional. Making it a test dependency excludes the test server from the published jar file. It would be probably better to provide a separate *-test.jar file, if you don't want to have the test server included as runtime dependency. WDYT?

**Comment by crispywalrus** [comment]
Building a test dependency would work, as long as the runtime dependency on curator is removed. For myself I intent to completely dike out the test servers and just run kafka an zookeeper for development anyway but I'd like to keep using the published artifacts.

**Comment by krasserm** [comment]
Ok, then let's go for an additional -test.jar. Do you want to make that contribution?

**Comment by crispywalrus** [comment]
I've updated my fork, and hence pr #22
